### PR TITLE
Edit VCV vowel map

### PR DESCRIPTION
**Pull request by adlez27**
Moved 1-char symbols to the end of the list so that 2-char symbols are correctly recognized first

### CODE REVIEW

**Comment by sdercolin** [comment]
Would you mind looking into the issue more to fix the script, so that we could handle it correctly without depending on certain orders of items in the map?

**Comment by adlez27** [comment]
I checked more closely and the order doesn't matter, as it appears to be sorting correctly by length. It seems the issue I had was actually caused by some common characters being missing from the default list. I'll revise my PR and check the CVVC default lists as well.

**Comment by sdercolin** [comment]
Changes LGTM, Thank you!
Could you please also bump up the versions of these two plugins?

**Comment by sdercolin** [comment]
💯

**Pull request merged**
